# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NmqxlvQQwzVRvUKtypuWwZDTOzjy521-
"""

import requests
import json

import datetime


headers = {'Content-type': 'application/json'}
current_year = datetime.datetime.now().year #get current year

#retreieve data between 2023 and current year
data = json.dumps({"seriesid": ['LNS14000000','CES0000000001', 'CES0500000002', 'CES0500000003', 'PRS85006092'],"startyear":"2023", "endyear":str(current_year)})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)