name: Run Python Script Monthly

# Schedule the workflow to run at 00:00 on the 1st day of every month
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools>=65.5.0
          pip install -r requirements.txt

      - name: Run script
        run: python Project.py
